LOAD_DATASET_ROOT="Cifar10"
PATH_CALLBACK="ResNet34_cifar10.pth.tar"
TENSORBOARD_LOG_DIR="Tensorboard_Writer"
PREDICTION_PATH="Prediction_Images"

LEARNING_RATE=0.01
LABEL_SIZE=10
BATCH_SIZE=100
EPOCHS=20
MAX_BATCH_TENSORBOARD_IMG=10

VALID_SIZE=10000

LOAD_CALLBACK=False
TRAIN=True
TEST=True
PREDICTION=True
VISUALIZE_TEST_PRED=True
